Fix -Wformat-security error
As -Werror flag is used in src/Makefile.am, next error occurs:

    gui.c: In function ‘gui_report_error’:
    gui.c:134:17: error: format not a string literal and no
                  format arguments [-Werror=format-security]
                  message);

Disable -Wformat-security in order to fix the build, before the code is
actually fixed.

Signed-off-by: Sam Protsenko <joe.skb7@gmail.com>